apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  name: ecs_cluster
  description: ecs terraform module
spec:
  type: terraform
  lifecycle: experimental
  owner: platform-team
  providesVariables:
    - environment
    - awsRegion
    - action
  dependsOn:
    - resource:asg
    - resource:cloudwatch
    - resource:data
    - resource:dynamo
    - resource:ecs
    - resource:iam
    - resourcecomponent:lambda
  environment:
   - my-company-dev

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: asg
  description: asg terraform module
spec:
  type: terraform
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  name: lambda
  description: asg terraform module
spec:
  type: terraform
  lifecycle: experimental
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cloudwatch
  description: asg terraform module
spec:
  type: terraform
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: data
  description: asg terraform module
spec:
  type: terraform
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dynamo
  description: asg terraform module
spec:
  type: terraform
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ecs
  description: asg terraform module
spec:
  type: terraform
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: iam
  description: asg terraform module
spec:
  type: terraform
  owner: platform-team


