apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  name: ecs_1.2.0
  description: ecs terraform module
ownedBy:
  - my-company-dev
spec:
  type: terraform
  lifecycle: experimental
  owner: platform-team
  providesVariables:
    - environment
    - awsRegion
    - action
  dependsOn:
    - asg.tf
    - cloudwatch.tf
    - data.tf
    - dynamo.tf
    - ecs.tf
    - iam.tf
    - lambda.tf
  environment: ecs-terraform-cluster
