apiVersion: backstage.io/v1alpha1
kind: ResourceComponent
metadata:
  name: ecs_1.2.0
  description: ecs terraform module
#  relations:
#    - type: memberOf
#      targetRef: environment:my-company-dev
spec:
  type: terraform
  lifecycle: experimental
  owner: platform-team
  providesVariables:
    - environment
    - awsRegion
    - action
  dependsOn:
    - resource:asg.tf
    - resource:cloudwatch.tf
    - resource:data.tf
    - resource:dynamo.tf
    - resource:ecs.tf
    - resource:iam.tf
    - resource:lambda.tf
  environment: my-company-dev
